[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
# Uncomment if needed
# tokio = {workspace = true}
async-trait = {workspace = true}
serde = {workspace = true}
# derive-new = {workspace = true}
# futures = {workspace = true}